# Generated by Django 3.0.3 on 2020-02-28 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20200214_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lower_primary',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='invalid phone number, phone number should be in the format of +254.', regex='[07]\\d{2}\\d{3}\\d{4}')]),
        ),
        migrations.AlterField(
            model_name='pre_primary',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='invalid phone number, phone number should be in the format of +254', regex='(\\+254)\\s*?(\\d{3})\\s*?(\\d{3})\\s*?(\\d{3})')]),
        ),
        migrations.AlterField(
            model_name='upper_primary',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='invalid phone number, phone number should be in the format of +254', regex='[07]\\d{2}\\d{3}\\d{4}')]),
        ),
    ]
