# Generated by Django 3.0.3 on 2020-03-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20200228_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolUpdateForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
            ],
        ),
    ]
