# Generated by Django 3.0.3 on 2020-03-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_auto_20200308_1008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
