# Generated by Django 3.0.3 on 2020-03-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_auto_20200310_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lower_primary',
            name='student_class',
            field=models.CharField(choices=[('Grade 3', 'Grade 3'), ('Grade 2', 'Grade 2'), ('Grade 1', 'Grade 1')], max_length=15),
        ),
        migrations.AlterField(
            model_name='lower_primary',
            name='student_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=15),
        ),
        migrations.AlterField(
            model_name='pre_primary',
            name='student_class',
            field=models.CharField(choices=[('One', 'Pre_primary 2'), ('Two', 'Pre_primary 1')], max_length=15),
        ),
        migrations.AlterField(
            model_name='pre_primary',
            name='student_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=15),
        ),
        migrations.AlterField(
            model_name='upper_primary',
            name='student_class',
            field=models.CharField(choices=[('Grade 6', 'Grade 6'), ('Grade 5', 'Grade 5'), ('Grade 4', 'Grade 4')], max_length=15),
        ),
        migrations.AlterField(
            model_name='upper_primary',
            name='student_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=115, null=True),
        ),
    ]
