# Generated by Django 3.0.3 on 2020-03-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_auto_20200316_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_primary_2',
            name='student_class',
            field=models.CharField(choices=[('Two', 'Pre_primary 2')], max_length=15),
        ),
    ]
