# Generated by Django 2.2.7 on 2020-02-14 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0008_auto_20200127_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_primary_performance',
            name='Environmental_activities',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='\\d{2}+\\s')]),
        ),
        migrations.AlterField(
            model_name='pre_primary_performance',
            name='Language_activities',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='\\d{2}+\\s')]),
        ),
        migrations.AlterField(
            model_name='pre_primary_performance',
            name='Mathematical_activities',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='\\d{2}+\\s')]),
        ),
        migrations.AlterField(
            model_name='pre_primary_performance',
            name='Psychomotor_and_creative_activities',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='\\d{2}+\\s')]),
        ),
        migrations.AlterField(
            model_name='pre_primary_performance',
            name='Religious_education_activities',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='\\d{2}+\\s')]),
        ),
    ]
