# Generated by Django 3.0.3 on 2020-03-09 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0009_auto_20200214_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lower_primary_performance',
            name='English_language_activities',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='lower_primary_performance',
            name='Environmental_activities',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='lower_primary_performance',
            name='Hygiene_and_nutrition_activities',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='lower_primary_performance',
            name='Indigenous_language_activities',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='lower_primary_performance',
            name='Kiswahili_language_activities',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='lower_primary_performance',
            name='Literacy_activities',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='lower_primary_performance',
            name='Mathematical_activities',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='lower_primary_performance',
            name='Movement_and_creative_activities',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='lower_primary_performance',
            name='Religious_education_activities',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='pre_primary_performance',
            name='Environmental_activities',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='pre_primary_performance',
            name='Language_activities',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='pre_primary_performance',
            name='Mathematical_activities',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='pre_primary_performance',
            name='Psychomotor_and_creative_activities',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='pre_primary_performance',
            name='Religious_education_activities',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='upper_primary_performance',
            name='Agriculture',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='upper_primary_performance',
            name='Creative_Arts',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='upper_primary_performance',
            name='English',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='upper_primary_performance',
            name='Home_Science',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='upper_primary_performance',
            name='Kiswahili_or_Kenya_Sign_Language',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='upper_primary_performance',
            name='Mathematical',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='upper_primary_performance',
            name='Physical_and_Health_Education',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='upper_primary_performance',
            name='Religious_education_activities',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='upper_primary_performance',
            name='Science_and_Technology',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='upper_primary_performance',
            name='Social_Studies',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')]),
        ),
    ]
