# Generated by Django 3.0.3 on 2020-03-16 17:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_auto_20200316_1700'),
        ('performance', '0010_auto_20200309_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upper_primary_performance_grade_6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('English', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Kiswahili_or_Kenya_Sign_Language', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Home_Science', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Mathematical', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Agriculture', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Science_and_Technology', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Creative_Arts', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Physical_and_Health_Education', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Religious_education_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Social_Studies', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Teachers_comment', models.TextField()),
                ('Student_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.Upper_primary_grade_6')),
            ],
        ),
        migrations.CreateModel(
            name='Upper_primary_performance_grade_5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('English', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Kiswahili_or_Kenya_Sign_Language', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Home_Science', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Mathematical', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Agriculture', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Science_and_Technology', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Creative_Arts', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Physical_and_Health_Education', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Religious_education_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Social_Studies', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Teachers_comment', models.TextField()),
                ('Student_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.Upper_primary_grade_5')),
            ],
        ),
        migrations.CreateModel(
            name='Pre_primary_performance_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Mathematical_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Environmental_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Psychomotor_and_creative_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Religious_education_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Teachers_comment', models.TextField()),
                ('Student_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.Pre_primary_2')),
            ],
        ),
        migrations.CreateModel(
            name='Lower_primary_performance_grade_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('English_language_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Literacy_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Kiswahili_language_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Mathematical_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Hygiene_and_nutrition_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Environmental_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Indigenous_language_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Movement_and_creative_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Religious_education_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Teachers_comment', models.TextField()),
                ('Student_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.Lower_primary_grade_3')),
            ],
        ),
        migrations.CreateModel(
            name='Lower_primary_performance_grade_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('English_language_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Literacy_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Kiswahili_language_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Mathematical_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Hygiene_and_nutrition_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Environmental_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Indigenous_language_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Movement_and_creative_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Religious_education_activities', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='only digits are required.', regex='^[0-9]+$')])),
                ('Teachers_comment', models.TextField()),
                ('Student_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.Lower_primary_grade_2')),
            ],
        ),
    ]
