# Generated by Django 3.0.3 on 2020-03-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioMesaage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sent_to', models.CharField(max_length=14)),
                ('Message_body', models.TextField(max_length=200)),
                ('Message_status', models.CharField(max_length=50)),
                ('Price_unit', models.FloatField()),
                ('Price', models.FloatField()),
                ('Message_sid', models.CharField(max_length=100)),
                ('Error_code', models.IntegerField()),
                ('Error_message', models.TextField(max_length=200)),
            ],
        ),
    ]
