# Generated by Django 3.0.3 on 2020-03-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_twiliomesaage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twiliomesaage',
            name='Price_unit',
            field=models.CharField(max_length=50),
        ),
    ]
