# Generated by Django 3.0.3 on 2020-03-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_auto_20200304_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twiliomesaage',
            name='Error_code',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='twiliomesaage',
            name='Error_message',
            field=models.TextField(default=False, max_length=200),
        ),
    ]
