# Generated by Django 3.0.3 on 2020-03-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_auto_20200304_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twiliomesaage',
            name='Error_code',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='twiliomesaage',
            name='Error_message',
            field=models.TextField(default=True, max_length=200),
        ),
    ]
