# Generated by Django 3.0.3 on 2020-03-04 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_auto_20200304_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twiliomesaage',
            name='Error_code',
        ),
        migrations.RemoveField(
            model_name='twiliomesaage',
            name='Error_message',
        ),
    ]
