# Generated by Django 3.0.3 on 2020-03-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_auto_20200304_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='mail',
            name='email_subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
