# Generated by Django 3.0.3 on 2020-03-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_auto_20200308_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='email_subject',
            field=models.CharField(max_length=100),
        ),
    ]
