# Generated by Django 3.0.3 on 2020-02-28 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20200228_0747'),
        ('attendance', '0002_auto_20200228_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_primary_1_attendance',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Pre_primary'),
        ),
    ]
