# Generated by Django 3.0.3 on 2020-03-09 18:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_delete_school'),
        ('attendance', '0003_auto_20200228_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upper_primary_attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField(default=False, verbose_name='Mondday')),
                ('tuesday', models.BooleanField(default=False, verbose_name='Tuesday')),
                ('wednessday', models.BooleanField(default=False, verbose_name='Wednessday')),
                ('thursday', models.BooleanField(default=False, verbose_name='thursday')),
                ('friday', models.BooleanField(default=False, verbose_name='Friday')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Upper_primary')),
            ],
        ),
        migrations.CreateModel(
            name='Lower_primary_attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField(default=False, verbose_name='Mondday')),
                ('tuesday', models.BooleanField(default=False, verbose_name='Tuesday')),
                ('wednessday', models.BooleanField(default=False, verbose_name='Wednessday')),
                ('thursday', models.BooleanField(default=False, verbose_name='thursday')),
                ('friday', models.BooleanField(default=False, verbose_name='Friday')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Lower_primary')),
            ],
        ),
    ]
