# Generated by Django 3.0.3 on 2020-03-10 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_delete_school'),
        ('attendance', '0004_lower_primary_attendance_upper_primary_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_primary_1_attendance',
            name='student_class',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.Pre_primary'),
        ),
    ]
