# Generated by Django 3.0.3 on 2020-03-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20200310_0903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pre_primary_1_attendance',
        ),
    ]
