# Generated by Django 3.0.3 on 2020-03-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_auto_20200310_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pre_primary_1_attendance',
        ),
    ]
